language: scala
scala: 2.12.8
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "QVUTq+yRi1HREy2jESW6PCYfStIGc1S9Q9vV+Do1LXTeMgwyPVevozH0EueGCpxDEr1pEELw+/+ycuIHZsHc54MyEj8n1qMc7j02BQLLcM1Wb+i2SEHpxWZyBCMZ+qH5KZBBk8IsyAzLRNUjliTaAI8Foe5GRczOJ++5FffpbRLHgXNAEjTjy/h2/IJkuikHn3juV6KbP89Xj5xfsfj0GevPSHTZjz0U7XYHmTMoDgerKJNVoCruz+Rmc5AxhycPv4cngFXdTe3QIGHws0fH2e0sofjG865WEGkJ0Heuk/hGr8vQNTtipCER8psqGqszTp1yeRHanZqJXsr4I6C2aTot8pnze7KTjQ5WDcXJfBoK2Be2SYwsZBfnfgBPgvLOeSnmjq5B633N3SgxAhhKs+HQQMXlLMzbtensD4cUw3GXnqXKGpoJ6eGmH9Q49kPpzkQQQllKO9l78NP1KF7HlQtb+7y2qhsH8qdIuOigF2lO11RtpRQsgCiKHdMo7/LeEYF4x0UoBAgMGCsbJyjlatI5y51iit57iKX8POS99Zb11esrwJPLLStIJA9wnF+M/q1ImGovviJRzpygQ7xO64xkP8m0oVLijXElDulciiVyLYQmxOoGQvkWVisQHSWv088cV2jt6m4lYPdv8iZPo/Irki5cthimiqeeL/n+7lM="
    # GITHUB_TOKEN
    - secure: "Ji/8G+0VcTd5zNavsAlTEztnDZ++qoQ9mFXfL3J16tny9it9wpz4jiComOJ80bWY/zxw9FNBNmkQUh7VhDfWAMd6qDxJs6f/my0YZ5tVWpabFo6N7ZAN4tnFQbkFhb+BYMOLnDT4dKeJN3pdRw3HOmYVWT0OuhfpQLxpkVjI29sytVD9iIDW8smCQJQx0UCN0ZdYpSOJ/gwmnuUNlfp5q/et6GuB5ekSyjGscqqej4TTDaEtnVL/HmFdkk6vooBHAwZv+6Yl2K0/Od+H5Ec7SrjASva4Tr8Drf8iTEXkEWCq2KTsQXCjyKah811dpNuYMkgWbFl/RdrJOYM2EnkrryqYCYo+QhmkK3NzzIbD6r5Opn7w0Bf0hf3ZaSWVrnsGtjNrF46WlLndALthh0CZIkc74KorbJJyUMIOty6DBE46LO2IHWXAo3igk9crkM+g3RUeyANZxfsSpUU+8r4XbWiOaiUho2OOyw7bWS6hNY1JWK1Gw2TKnA/+tWV46jNZi4VUxsuL878vAjqwfbwrUr5zluVtu53H+OD53a9eMDHRgw49Mtx5JTLEXljhlUUnQ0x/EKlLJKL8QUOY81s3cwQfDuxHNqELhpJYLyWNaYWqG51N6pHpfEZykLeDR7zg+gP2EH1/iMKOyw+ZUOYqZ5N+/gO4nCQUaOCnVQeIO0A="
    # GITHUB_ACCESS_TOKEN
    - secure: "p+JxBWvRAWMePNRWMx5ty2C++TuOku10rLwqTFqPq3L5EkUg013S0if0QhHM3BbpXKGqjWhcJqQuAEVOT+42dIdO4VV6g7ShXeIoMcOVKtWanKaM7xUyBlwdTRkt17hKI0ulfRlHEPcPwdMbMSW1oP5/uQmUtSZLhqgS2hjL9MKjnuu6+as0ngzce4+b7AuD7nAwf+OJfPgMekSMz4CmaO7rUD/HtURiPIIVxkerckBLNLS1W6xNIsYPAjSkhh4yLWWOm1LiVVrMc7FExQnmjlCGuGUq3CjwFFCr8rsXJgM/P7EvqSG9d4zRmBg8nBz3x4r12jCEgd9y4uoFWnyKaprsApD5o+7RI89lxUNPOKVTmk8yfXY+MPboRwB0EbHgNv8aAUf+yGqQ8373UJhlbPrYflB1Txsnduv5CK+c8d//sc5dmyJXT0hNR42avU77gd7t3lr33UhOgJifXdUOqvwUQKGURwbfQXnoKtICPjcANegQhWKWFRFCOl39O5UCfPgashluRK4ULEngUv8gtPb/xrpQaKaOjfgn7Lh0Id354bRH92zC5Vfu40zRRMfnzltVLIfL3yUDZZyeEvj44ozwLp7JM5EyKjdHApUD3wVGic5dILAz1/ZlVamOfjQ4biDTSfrpy5DKDHeLkhlV/3/plC96YkUeNitXS6fd7Zw="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "AJ7/bD2aFq1cxuKkpM+UscO1VsDoP1c3D5tIZYomK8Ys2w151trmeI+D+LOSF5mEfso8y1Q/0ejT9M09C3UXYtLo3jvegJZTw1HTOk9s0JQuoZTkUSs0JzFH5RyPdl66rXqTTtgiwIMZdH18Dd7It0M6fntDJ9n54OVoq9veQl90i/zmPar7AVhOIaTiZWUKrWjdPeLZcMBqGtPqhq1wq4p+0gYtOLONO6gk0rljykvWu0uyQhOKg1AlIidNrHTaEw3TjVP+/q+BpENzcIWK8Fk4ieP3gnvXag/TqFG4bfVJKRBsiDMwsLYQxJsHBlG6IjLhUrJN9Wf3zuZC+hcoZTq8JxKlhXg+sXM+5xtAWfL/7QzWiyyoxKRVA8lEk+ta29xOL9M4WkizNxg6B0EAtyREtZ+kx7etKo1KJu5e/3+7KK82G3QqdWIuuXFIh9fhtvfG/l3CyytE0IZpUfNQc5sM9Jk+B0dWVRrn16FnDRcgOCKG3tCrvTXEFZReQ9traP+83QUrvzRrl1PWeJ2hzppGZ3qqMv5ZLssS7L/5zdt77GEoD4KenbW6FqsYy98oq4KDWWBHamd8ScOxMIbRh3+q1M3Akkl6LWLHGk5D5Tooy2PxogayZWbBNnz2FC3iuTfA4CTNDOq85yfJFIFV54gAhyiQWuS3EuvHM/12xUY="

    # key for nopassword ($key_19403187e0)
    - secure: "pD4xrn4n0tFKFZG4jSVEa3+70OBnHeNTQN3OkT0hZseyQU7N2aJJMc7oYfQr2pmT34+gbYv5KtdnBOacnGS5N30plBp1B73S5z95YWPAZoVqqNPvdmGVWx1+Ik3HnbJppCZVR8fNRnyGZ4EF3D/cwU3aOj3S+kr9zG61WhlWhRln1SSJ8oubsq9pvrlptZFNIl/cFodl2IZ8TsZAUcxCbxifQJn7VqAS25ABY6KBb8Nh9T8KPny6aR65zblLvg+ea9xnBSiuJH1ze7K0drAHVQrZIGkCV2hluH/vHUFhszNmTPCHZcKL7i3ZSGVaqZduU5OuosspQRaNMy9VbBhMb4o0xWYdlesaL7TQP4cd4BelRt0qKAh94/eHGctBDyZzvdnzKjiwoSd8j1M04VfQ/0Y/ierosg9HR76t7Zav6YBByoYki4/tX5fh7HhoPhQELr2xKKQZn/w+5t8lGp8HDXeT1eSGMIorCc2nXkKCGxz7wKyHve4gvIwZFwwe0YTR0T4iJrvq//deIrkizp6uMuQx+ssCZ6l5ctBtfJCnNmMyiVXxXNiyvJFlwOcXbbaPX8H0MFjbDOXQXXNQTjfswmDLYozenQRat4ZnuZ0cRoeMpoiBpPJZR2zXqWlMII1oqXxFT0MFq5Y1PPvBykg5frJG//mJj9nqk1spDzwKF1M="
    # initialization vector for nopassword ($iv_19403187e0)
    - secure: "hO8HLBfx9Ka20LlYY7UzbwQsEjRwi9dtloi1H3W1a/mrlMdjjYKAKHwn+g6ojn+6Sgs4c8jEyfImpUnK+mG8kRGb0PfwHuBvmhZhQmE1ddqEJkCffBZSX0VnIalp3IDYoYSmesHMH+8D8uT0TK20iwHEfg1dpLW8XfVlQJRNv1c/0f51igOurb3kIy0MHRRdD0FjXp5N60H6fGPqx8NZ/UMV0VklGz+pj9Ye2i+TSrCmIlx1d/+07etjJigvBhx+lF9R5riL5LVenUfxOhxEP0k6j3E9cEFoOJd0w62w1hcTteU5J/LigaL+DSqWZ3AzHtw/uobxzpqNaVqv4BX5lp36LCHPp+V5DHfGfhRmUg7UKILy5wNBVfqP5cpJfjJ1y7qOkyTJ29owaRByiMxPwrn+ZoyACMCJEUDd8EiOYJXmjmi6cAyOXG+DBrwbzsrTw02fQyf/Z7QeYbvPyX/Hga3CDsmSZi60CDauH3xkmZaSmCnaUI6OWmcPgyvcGf9YFG+t58Yb+ljh5yYfnLWhAlJsMY19wj6Gzm7Zd4SJ/OGSc7nrPCsCyPqeOhdmvvqJXEBpHADoDg6B6TDhsBbHf8NkHoebxXJ0ONliBk+wdDDgidKanEnxH2W6P709XIP0i4MczayYM7AKb2orTBOP9ZTnrjOVHW12IKJd0CgWuHw="
    # key for password ($key_9812a889f5)
    - secure: "vFybrqkpEHBegrOVrLkOHYtdmtmn5qq344LqzeU1nPM7jHtX9RG/vsbnSVOWtrSO6f052UNkzzi3tVuHCCKpiyXYPN+vSfc1Tw1u2pcP3Wq98EQ3t+T4kGcbT4OGQqzHn8cbEJvxn23Oob010f5yBeFnXhj/Yo6nPMdjfFUDrynYzGyayi9fYf1L9KOmusEg8+S+PPh0u9Uwom+yb4PEnz9OzZUyjDSkkKcpsbYI4t+/q/3wf3id91A2zSad8eej5ni/Q74FA/0+/l3t/CuSiltndwGeoqh+rBAj7z2qgwyfG2mJ+JPiI6gH7yBgrwovrkHWwQwzytLUSPQht6KD4p4gs3JA27iuLjRDLVSmYBei4KF+3oNcmrY9LthPddWRWItzGZ9XjBbHGTc54DMlnuAiYYOw4WU2bHrctaHTeyemwwRRjt0Y5iugpFpDF4HvDd6YCR1MbgDwAQ6pG9dcu8q/ndoXUo3OfynM9zkDgVB613r21S5530bFpVJBRTyH6cncD3QbD8NuC/+72NpSFYxEWXvlDYc/c/OzzeDB0iFa/Sw87aVOPo2g+gOzscfE2FonM2iKsacPgFXwV0byRdsC1rN2trwRv5rGK/ZJUH2MslPQgvow5moAR7AnO8tVEaMtrmgOJTBuGGXubt3LUf2qvWxDvoK1qHXWIKzQ4GE="
    # initialization vector for password ($iv_9812a889f5)
    - secure: "e6nf3RAbAMn8u6uGWVFZks9bzqFwsooefqUKlrtTrLjgGM0gq+DyzdLd3CEqOfsyK3JnuufsytOQDXJVagGzkYeMCvi4QcOq/gJAFnRCKAygcnlusD3rxpiwPNJLebkoUPlThkA9vFPmW8Jut8RUeCiMUO1fjKzDHSIFgyZUmjw8jMrEJboUWl8jWmBVuo7QBSnvgjbUI2TKAVz36OG50glaeKoHq/B3JR1PaH52CxrMnPuGQXy2h0fsS5PDrDkl5NWTjrMCLMjtzOI/W1ABqODyNwMZ89JjB3pgzhnK26N23J98HCX1862+USlIzPEFiwSkW5OC9zCE/nzs1l/iIhmdwhO2hDj1qaX7b+4dzMFyAk/qe7BTKfbi39L/P5Ti7CM0KgZ5YYf169Q935eQjifUpZxN0Zrn+JoP7ulxCGnXbw3kpCuHlrhRqRcx3sUrqHDMkq0aKQEFQ12TSQ3RMT2LWhIm9rRMfFHYZUFJLT0Uu+KDdtGzA1XpPBn/4JnupG9OBAe95trDdSiwvzCMU+c3soXrXMHxPZF5S1Kyh2oL7A1PE8nh89xoCKc8FOSkqDUQz88UbROaWnp8/FtIRofhvfp2iL1uge5ygG1cQ95VwIHDWAr5Azmb7pRvQoaXmfX1cQWLiZaRXl3gAjjYgKba5mHqHUAwKzsVu6TNagU="

    # FS2_SSH_TEST_PASSWORD
    - secure: "rhGjMdiOdrZ9g0XdiwSqeZhJFGbQf/w5x+zLzYi3Zk17jInUIX0VuatIKA64/sc4ZN+T0JaWcas67ChxgnbFYjBLiq7q3rhb2+rrPlT949bKJk5Fr3ffbyh16K0+5vlhqwq1qobch0Cwpg3HxXw3N5Vf5/Ep31tdspIZoTn/29ZiLZ8StBJP5NqRn1w4Lt0qRRQW7tAyhozZIwQZbcLLO+HKc/i5JQFlCrh5h0OIq1oabjTOg3CVMw8J8Jt0sd/EvXgCI57wps2fjZVFd2ChKY7CFF30gtzz3529TjCC8bc8lFW4mT4w1UjnQdjvY0KI5YmuJVNmE9gCHSmrN21vsbP8aPqO+jhRen96Ko8UcsgQ4N3vjrvZ6RiCkKy0VUTapf4aMVpQDqydcxJAS7D2pSX9EJEUu3xiJX/XrJ/FvAbMBDP3yGJLjdYOrer8XyjoJh0vTiJIS3e4HXvZVYYOGCXmQSIjxQhGnii5o4z6QuzxGs7ORg+sS5ynwYmEy2JCiJf0vSkB2in7g88DyVYpfm1HRQoGjX/CZKAyXdPy6U0uw7iadCRNUFqwc/Rcj0Ms9jeG/E3vxsufymTHZTmWICtWmp9i5hZmdNfKWnSPY3EPl4h+wocLQC5tLfeBUeesizSlGi0XZcZEpRlMjDMNuqThp3c/TMTs8SUD2h6heTA="

before_install:
  - set -e
  - cd keys
  - 'openssl aes-256-cbc -K $key_19403187e0 -iv $iv_19403187e0 -in "nopassword.enc" -out "nopassword" -d'
  - 'openssl aes-256-cbc -K $key_9812a889f5 -iv $iv_9812a889f5 -in "password.enc" -out "password" -d'
  - cd ..

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/fs2-ssh';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/

before_cache:
  - find "$HOME/.sbt/" -name '*.lock' -print0 | xargs -0 rm
  - find "$HOME/.ivy2/" -name 'ivydata-*.properties' -print0 | xargs -0 rm
